# Generated by Django 4.1 on 2022-09-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_details', models.CharField(max_length=800)),
                ('product_price', models.IntegerField()),
                ('product_loc', models.CharField(max_length=200)),
            ],
        ),
    ]
